import Foundation
import simd
import WorldGeo
import WorldMap

/// One house archetype of house-archetypes-v1 (R approved 2026-10-07, binding): the generator values of one
/// sheet, read by key from the bundled shared mock values (`Profiles/mock-values.json`, generated by
/// Tools/lookloop/compile_mocks.py) under "house-archetypes-v1/archetypes.<id>.…". Profile house types name their
/// archetype (`HouseType.archetype`); the archetype then supplies the type's palette variants, roof family and
/// pitch range, floor-to-floor height, foundation height and porch depth. Real OSM tags and geometry always win:
/// mapped levels, height, roof shape and colours override these defaults, and a mapped footprint is never resized.
/// The pack labels all of these values proposals; the labels stay with the values in the mock values file.
public struct HouseArchetype: Sendable, Equatable {
    /// One `colourVariations[n]` entry: wall, trim, roof and daytime glass.
    public struct Variant: Sendable, Equatable {
        public var wall: String
        public var trim: String
        public var roof: String
        public var glass: String
    }

    /// One `buildingPartsProposal` volume (split-level main block and wing).
    public struct Part: Sendable, Equatable {
        public var fullFloors: Int
        public var eaveHeight: Double
    }

    public var id: String
    public var metro: String
    /// `generatorWeightPctProposal`: the metro fallback mix weight (not a measured share).
    public var weightPct: Double
    public var footprintWidth: Double
    public var footprintDepth: Double
    public var foundation: Double
    public var floorToFloor: Double
    public var eaveHeight: Double
    public var totalHeight: Double
    public var porchDepth: Double
    public var setback: Double
    public var fullFloors: Int
    /// hipped | gabled | flat (the pack's `pyramidal` is a hip on a square plan).
    public var roofFamily: String
    public var pitchDegrees: Double
    public var pitchRanges: [[Double]]
    public var variants: [Variant]
    /// Detail tiers by building height on screen: under `farBelowPx` silhouette and colour only; from there to
    /// `nearAbovePx` porch/bay/carport voids; above it dormers, openings and broad trim.
    public var farBelowPx: Double
    public var nearAbovePx: Double
    public var parts: [Part]

    static let prefix = "house-archetypes-v1/archetypes."

    /// The archetype's values from the shared mock values, nil when the archetype or a required value is missing.
    public static func load(_ id: String, mock: MockValues? = .bundled) -> HouseArchetype? {
        guard let m = mock else { return nil }
        let p = prefix + id + "."
        func n(_ k: String) -> Double? { m.number(p + k) }
        func s(_ k: String) -> String? { m.string(p + k) }
        guard s("id") == id, let w = n("footprintWidthM".dims), let d = n("footprintDepthM".dims), let f = n("foundationAboveGradeM".dims),
              let ff = n("floorToFloorM".dims), let eave = n("eaveHeightM".dims), let total = n("totalHeightM".dims), let porch = n("porchDepthM".dims),
              let setback = n("setbackM".dims), let floors = n("storeys.fullFloors"), let family = s("roof.family"),
              let pitch = n("roof.pitchDegrees") else { return nil }
        var ranges: [[Double]] = []
        while let lo = n("roof.allowedPitchDegreeRangesProposal[\(ranges.count)][0]"),
              let hi = n("roof.allowedPitchDegreeRangesProposal[\(ranges.count)][1]") { ranges.append([lo, hi]) }
        var variants: [Variant] = []
        while let wall = s("colourVariations[\(variants.count)].wallHex"), let trim = s("colourVariations[\(variants.count)].trimHex"),
              let roof = s("colourVariations[\(variants.count)].roofHex"),
              let glass = s("colourVariations[\(variants.count)].windowGlassDayHex") {
            variants.append(Variant(wall: wall, trim: trim, roof: roof, glass: glass))
        }
        var parts: [Part] = []
        while let pf = n("buildingPartsProposal[\(parts.count)].fullFloors"), let pe = n("buildingPartsProposal[\(parts.count)].eaveHeightM") {
            parts.append(Part(fullFloors: Int(pf), eaveHeight: pe))
        }
        guard !variants.isEmpty, !ranges.isEmpty else { return nil }
        return HouseArchetype(
            id: id, metro: s("metro") ?? "", weightPct: n("generatorWeightPctProposal") ?? 0,
            footprintWidth: w, footprintDepth: d, foundation: f, floorToFloor: ff, eaveHeight: eave, totalHeight: total, porchDepth: porch,
            setback: setback, fullFloors: Int(floors), roofFamily: family == "pyramidal" ? "hipped" : family, pitchDegrees: pitch,
            pitchRanges: ranges, variants: variants,
            farBelowPx: n("detailTiers[0].buildingHeightPx.maxExclusive") ?? 6,
            nearAbovePx: n("detailTiers[2].buildingHeightPx.minExclusive") ?? 20, parts: parts)
    }

    /// Every archetype in the bundled mock values, by ID.
    public static let bundled: [String: HouseArchetype] = {
        guard let m = MockValues.bundled else { return [:] }
        let ids = m.strings.keys.compactMap { k -> String? in
            guard k.hasPrefix(prefix), k.hasSuffix(".id") else { return nil }
            let mid = k.dropFirst(prefix.count).dropLast(3)
            return mid.contains(".") ? nil : String(mid)
        }
        var out: [String: HouseArchetype] = [:]
        for id in ids { out[id] = load(id, mock: m) }
        return out
    }()

    public static func named(_ id: String?) -> HouseArchetype? { id.flatMap { bundled[$0] } }

    /// The allowed pitch range that holds the sheet's pitch (the first range otherwise).
    public var pitchRange: [Double] {
        ranges(containing: pitchDegrees) ?? pitchRanges[0]
    }

    func ranges(containing x: Double) -> [Double]? { pitchRanges.first { $0[0] <= x && x <= $0[1] } }

    /// The roof family as a profile roof mix (one family; a mapped roof:shape still wins).
    public var roofMix: StyleProfile.RoofMix {
        .init(gabled: roofFamily == "gabled" ? 1 : 0, hipped: roofFamily == "hipped" ? 1 : 0, flat: roofFamily == "flat" ? 1 : 0)
    }

    /// Frontage / depth of the sheet's footprint (the same measure as `frontageAspect`).
    public var aspect: Double { footprintWidth / footprintDepth }
    public var area: Double { footprintWidth * footprintDepth }

    /// Building height on screen (px) for a camera at `distance` metres with a frame `frameHeightPx` tall and
    /// vertical field of view `fovDegrees` (pinhole, building facing the camera).
    public static func screenHeightPx(height: Double, distance: Double, frameHeightPx: Double, fovDegrees: Double) -> Double {
        height * frameHeightPx / (2 * tan(fovDegrees * .pi / 360)) / max(distance, 0.01)
    }

    /// The distances (m) at which this archetype's sheet height crosses the near (> 20 px) and far (< 6 px) tiers.
    public func tierDistances(frameHeightPx: Double, fovDegrees: Double) -> (near: Double, far: Double) {
        let f = frameHeightPx / (2 * tan(fovDegrees * .pi / 360))
        return (totalHeight * f / nearAbovePx, totalHeight * f / farBelowPx)
    }
}

private extension String {
    var dims: String { "dimensions." + self }
}


extension StyleProfile.HouseType {
    /// This type with its archetype's values (by key from the shared mock values): palette variants
    /// [wall, trim, door, roof] (doors stay the profile's; the pack has no door colours), roof family, the allowed
    /// pitch range holding the sheet pitch, floor-to-floor height and porch depth. Unchanged without an archetype.
    public func resolvingArchetype(_ a: HouseArchetype?) -> StyleProfile.HouseType {
        guard let a else { return self }
        var t = self
        let doors = colors.map { $0.count > 2 ? $0[2] : "#5A6B6B" }
        t.colors = a.variants.enumerated().map { i, v in [v.wall, v.trim, doors.isEmpty ? "#5A6B6B" : doors[i % doors.count], v.roof] }
        t.roof = a.roofMix
        t.pitch = a.pitchRange
        t.perFloor = [a.floorToFloor, a.floorToFloor]
        t.porch.depth = [a.porchDepth, a.porchDepth]
        return t
    }
}

extension StyleProfile {
    /// The profile with every house type that names an archetype resolved from the shared mock values.
    public func resolvingArchetypes() -> StyleProfile {
        var p = self
        p.houseTypes = houseTypes.map { $0.resolvingArchetype(HouseArchetype.named($0.archetype)) }
        return p
    }
}

/// Archetype choice tuning (`look.json` "archetypes"): P2 mapping thresholds that the pack does not give.
public struct ArchetypeTuning: Codable, Sendable, Equatable {
    /// Soft frontage-aspect preference: the sheet's width/depth divided and multiplied by this factor.
    public var aspectFactor: Double
    /// Soft footprint-area preference as multiples of the sheet's width × depth.
    public var areaRange: [Double]
    /// Weight multiplier floor for a type whose roof mix has no share of a mapped roof:shape.
    public var roofTagFloor: Double
    /// Split-level: share of the frontage taken by the two-storey main block (judged from the sheet artwork).
    public var splitMainShare: Double
    /// Split-level: only footprints at least this rectangular (and with one roof rectangle) are split.
    public var splitMinRectangularity: Double
    /// Far tier (6–20 px): porch void darkness as a wall shade when the type has no house-contrast porch colour.
    public var farPorchShade: Double
    /// Reference phone frame for the detail-tier mapping (px tall) and vertical field of view (degrees).
    public var tierFrameHeightPx: Double
    public var tierFovDegrees: Double

    public static let fallback = ArchetypeTuning(aspectFactor: 1.5, areaRange: [0.5, 1.8], roofTagFloor: 0.1, splitMainShare: 0.45,
                                                 splitMinRectangularity: 0.9, farPorchShade: 0.35, tierFrameHeightPx: 565, tierFovDegrees: 50)
}

/// A house family choice with its evidence: every archetype is inferred, never observed.
public struct HouseChoice: Sendable {
    public var type: StyleProfile.HouseType
    public var situation: String
    /// The archetype ID (house-archetypes-v1), nil for types outside the pack.
    public var archetype: String?
    /// Probability of this type in the weighted pick (0–1): the chosen weight over the pool's total weight.
    public var confidence: Double
    /// What the choice used: levels, height, roof:shape, footprint, shared walls, fallback mix.
    public var evidence: [String]
}

extension BuildingGenerator {
    static var archetypeTuning: ArchetypeTuning { LookSpec.bundled?.archetypes ?? .fallback }

    /// Expands a situation's weights: plain type IDs keep their weight; "@archetypes" splits its weight among the
    /// profile's archetype types by the pack's metro fallback mix (`generatorWeightPctProposal`, read by key) and
    /// "@archetypes:N" among those whose default floor count is N (keeps measured floor-group totals). Each type's
    /// share is scaled by its `archetypeShare` (default 1, 0 = only by explicit rule). Only `include` types count.
    func expandWeights(_ weights: [String: Double], include: (StyleProfile.HouseType) -> Bool) -> [(StyleProfile.HouseType, Double)] {
        var out: [(StyleProfile.HouseType, Double)] = []
        for key in weights.keys.sorted() {
            let w = weights[key]!
            if key == "@archetypes" || key.hasPrefix("@archetypes:") {
                let group = key.split(separator: ":").dropFirst().first.flatMap { Int($0) }
                let members = profile.houseTypes.filter { t in
                    guard let a = HouseArchetype.named(t.archetype), include(t) else { return false }
                    return (group == nil || t.floors.first == group) && a.weightPct * (t.archetypeShare ?? 1) > 0
                }
                let ws = members.map { HouseArchetype.named($0.archetype)!.weightPct * ($0.archetypeShare ?? 1) }
                let total = ws.reduce(0, +)
                guard total > 0 else { continue }
                for (t, x) in zip(members, ws) { out.append((t, w * x / total)) }
            } else if let t = profile.houseType(key), include(t) {
                out.append((t, w))
            }
        }
        return out
    }

    /// House family choice from data: OSM tags and geometry first (levels pick the situation and eligible floor
    /// counts; footprint aspect, rectangularity, frontage and area; a mapped roof:shape; shared walls via
    /// `building=semidetached_house`), then the situation's weights, where "@archetypes" entries carry the metro's
    /// fallback mix. Year built is not used (no GREEN-licensed source yet). Stable per building.
    public func houseChoice(for b: Building, shape: FootprintAnalysis, frontEdge: Int?) -> HouseChoice {
        if let id = forcedHouseType, let t = profile.houseType(id) {
            return HouseChoice(type: t, situation: "forced", archetype: t.archetype, confidence: 1, evidence: ["forced"])
        }
        let ring = b.footprint.outer
        var broadFront = false
        if let e = frontEdge {
            let (_, dir, _, _) = Self.edge(ring, e)
            broadFront = abs(simd_dot(dir, shape.obb.u)) > 0.85
        }
        let key = situation(b, shape: shape, broadFront: broadFront)
        let weights = profile.typeRules[key] ?? profile.typeRules["unknown"] ?? [:]
        let aspect = shape.obb.halfWidth > 0 ? shape.obb.halfLength / shape.obb.halfWidth : 1
        let frontage = frontageAspect(ring, shape: shape, frontEdge: frontEdge)
        let levels = b.levels.map { Int($0.rounded()) }
        func eligible(_ t: StyleProfile.HouseType) -> Bool {
            if families.grammar(t.id).role == "block" { return false }
            if let l = levels, l > 0, !t.floors.contains(l) { return false }
            if let m = t.minAspect, aspect < m { return false }
            if let m = t.maxAspect, aspect > m { return false }
            if let q = t.minRectangularity, shape.rectangularity < q { return false }
            if t.broadFrontage == true, !broadFront { return false }
            return true
        }
        let all = expandWeights(weights) { _ in true }
        let candidates = expandWeights(weights, include: eligible)
        let pool = candidates.isEmpty ? all : candidates
        guard !pool.isEmpty else {
            let t = profile.houseTypes.first { families.grammar($0.id).role != "block" } ?? profile.houseTypes[0]
            return HouseChoice(type: t, situation: key, archetype: t.archetype, confidence: 0, evidence: ["default"])
        }
        let tuning = Self.archetypeTuning
        let tagged: KeyPath<StyleProfile.RoofMix, Double>? = switch b.roofShape {
        case "gabled", "saltbox", "gambrel", "mansard": \.gabled
        case "hipped", "pyramidal", "half-hipped", "side_hipped": \.hipped
        case "flat": \.flat
        default: nil
        }
        func weight(_ item: (StyleProfile.HouseType, Double)) -> Double {
            let g = families.grammar(item.0.id)
            let a = HouseArchetype.named(item.0.archetype)
            let aspectPref = g.aspect ?? a.map { [$0.aspect / tuning.aspectFactor, $0.aspect * tuning.aspectFactor] }
            let areaPref = g.area ?? a.map { [$0.area * tuning.areaRange[0], $0.area * tuning.areaRange[1]] }
            var w = item.1 * HouseFamilyGrammar.fit(frontage, aspectPref) * HouseFamilyGrammar.fit(b.footprint.area, areaPref)
            if let k = tagged { w *= max(tuning.roofTagFloor, item.0.roof[keyPath: k]) }
            return w
        }
        var r = b.ref.random("house-type")
        let chosen = r.pick(pool) { weight($0) }
        let total = pool.reduce(0) { $0 + max(0, weight($1)) }
        // The same type can enter the pool twice (explicitly and through a group): its confidence is its total.
        let mine = pool.filter { $0.0.id == chosen.0.id }.reduce(0) { $0 + max(0, weight($1)) }
        var evidence: [String] = []
        if levels != nil { evidence.append("levels") } else if b.height.source == .heightTag { evidence.append("height") }
        if tagged != nil { evidence.append("roof:shape") }
        evidence.append("footprint")
        if b.type == "semidetached_house" { evidence.append("sharedWalls") }
        if weights.keys.contains(where: { $0.hasPrefix("@archetypes") }) { evidence.append("fallbackMix") }
        return HouseChoice(type: chosen.0, situation: key, archetype: chosen.0.archetype,
                           confidence: total > 0 ? min(1, mine / total) : 0, evidence: evidence)
    }
}

/// Clips a ring to the half-plane `dot(p - origin, normal) >= 0` (Sutherland–Hodgman, one edge).
func clipHalfPlane(_ ring: Ring, origin: LocalPoint, normal: LocalPoint) -> Ring {
    guard ring.count >= 3 else { return [] }
    var out: Ring = []
    for i in 0..<ring.count {
        let a = ring[i], b = ring[(i + 1) % ring.count]
        let da = simd_dot(a - origin, normal), db = simd_dot(b - origin, normal)
        if da >= 0 { out.append(a) }
        if (da >= 0) != (db >= 0) {
            let t = da / (da - db)
            out.append(a + (b - a) * t)
        }
    }
    return out
}
