import Foundation

/// Renderer-neutral look values beyond the lighting bible and the rain pack (`Profiles/look.json`):
/// water, sky, wet paving and shadow range. Both renderers read them; see docs/look-spec-changes.md.
public struct LookSpec: Codable, Sendable {
    public struct Water: Codable, Sendable {
        /// How much of the water's colour is the reflected sky, clear and overcast (blended by cover).
        public var skyReflectClear: Double
        public var skyReflectOvercast: Double
        /// Saturation left in the water under full overcast.
        public var overcastSaturation: Double
        /// Ripple ring strength on open water while it rains.
        public var rainRipples: Double
        /// Brightness of the reflected sky under full overcast (a storm lake reads dark slate, not light grey).
        public var overcastReflectGain: Double
        /// Style profile → lake-winter-v1 water profile for the shore band (generator).
        public var shoreProfiles: ShoreProfiles?
    }
    public struct ShoreProfiles: Codable, Sendable {
        public var order: [String]
        public var profiles: [String: String]
    }
    public struct Sky: Codable, Sendable {
        /// Width of a cloud edge in noise units, clear sky and full overcast (soft edges as the deck closes,
        /// so a gap never reads as a cut-out shape).
        public var cloudEdgeClear: Double
        public var cloudEdgeOvercast: Double
    }
    /// Departure from the rain pack (owner, 7 Oct): its ≤12% paving darkening read dry on the phone, so
    /// the pack's concrete and asphalt darkening is scaled by `darkenScale` (capped at `darkenMax`).
    public struct WetPaving: Codable, Sendable {
        public var darkenScale: Double
        public var darkenMax: Double
        public var surfaces: [String]
    }
    /// Phone-size house contrast (generator; owner 7 Oct): house-contrast-v1 swatches per house type, read by
    /// key from the bundled shared mock values (`Profiles/mock-values.json`, generated by
    /// Tools/lookloop/compile_mocks.py); look.json holds only the family mapping and the band geometry.
    public struct HouseContrast: Codable, Sendable, Equatable {
        public struct HouseType: Sendable, Equatable {
            public var wall: String
            public var brick: Bool
            public var trim: String
            public var roof: String
            public var soffit: String
            public var porchShadow: String
            /// Daytime window glass (night lighting keys off the glass flag).
            public var glass: String
            /// Eave/cornice shadow brightness relative to the wall (wall = 1).
            public var eaveShadow: Double
        }
        /// Height (m) of the wall band under eaves and cornices that fades to `eaveShadow`.
        public var eaveBandHeight: Double
        /// Family ID → house-contrast-v1 type; "flat" = chicago_two_flat below three storeys, chicago_three_flat from three.
        public var families: [String: String]
        /// Chicago brick families whose walls take the pack's brick wall swatches (seeded per building).
        public var brickWallFamilies: [String]?

        /// The type's values from the shared mock values, nil when any is missing.
        public func values(_ type: String) -> HouseType? {
            let m = MockValues.bundled
            func hex(_ surface: String) -> String? { m?.string("house-contrast-v1/houseTypes.\(type).surfaces.\(surface).hex") }
            guard let wall = hex("wall"), let trim = hex("trim"), let roof = hex("roof"), let soffit = hex("soffit"), let porch = hex("porch_shadow"),
                  let glass = hex("window_glass_day"),
                  let eave = m?.number("house-contrast-v1/houseTypes.\(type).surfaces.eave_shadow.relativeBrightness") else { return nil }
            let brick = m?.string("house-contrast-v1/houseTypes.\(type).wallMaterial") == "brick"
            return HouseType(wall: wall, brick: brick, trim: trim, roof: roof, soffit: soffit, porchShadow: porch, glass: glass, eaveShadow: eave)
        }

        /// The pack's brick wall swatches (types whose wall material is brick), in a stable order.
        public var brickWalls: [String] {
            ["chicago_three_flat", "chicago_two_flat", "chicago_bungalow", "workers_cottage"].compactMap { values($0) }.filter(\.brick).map(\.wall)
        }

        public func type(family: String?, floors: Int) -> HouseType? {
            guard let f = family, let id = families[f] else { return nil }
            return values(id == "flat" ? (floors >= 3 ? "chicago_three_flat" : "chicago_two_flat") : id)
        }
    }
    /// Sun shadow coverage from the camera (RealityKit fits its cascades inside it): normal and
    /// below `lowSunBelowDeg` of sun elevation, when shadows grow long.
    public struct Shadows: Codable, Sendable {
        public var rangeM: Double
        public var lowSunRangeM: Double
        public var lowSunBelowDeg: Double
        /// Beyond the range, lawns and paths darken under the canopy map shifted along the sun by a
        /// typical crown's shadow (`blobCrownHeightM`), by `blobStrength` in full direct sun.
        public var blobStrength: Double
        public var blobCrownHeightM: Double
    }
    /// Engine calibration for the daytime master (not look values: those come from mock-values.json):
    /// key and fill multipliers that bring a neutral patch's shadow/lit ratio to the master's.
    public struct DaytimeMasterCalibration: Codable, Sendable {
        public var key: Double
        public var fill: Double
        /// The master's "+0.35 EV once" realised as the auto-exposure target: the four approved heroes'
        /// measured mean display brightness (Y8, 16:9 picture area). A gain on top of our auto exposure
        /// overshot the heroes by ~15 Y8 (they brighten far less than 0.35 EV over the captures).
        public var exposureTargetY8: Double
    }
    public var daytimeMaster: DaytimeMasterCalibration
    /// Projected-size building LOD (owner 7 Oct, with P2's house-archetypes-v1 detail tiers read from
    /// mock-values.json): the frame height the tiers were measured on and the near band (3D metres).
    public struct BuildingLODSpec: Codable, Sendable {
        public var frameHeightPx: Double
        public var nearDistanceM: Double
    }
    public var buildingLOD: BuildingLODSpec?
    public var water: Water
    public var sky: Sky
    public var shadows: Shadows
    public var wetPaving: WetPaving
    public var houseContrast: HouseContrast?
    /// House archetype choice and tier tuning (house-archetypes-v1 mapping values the pack does not give).
    public var archetypes: ArchetypeTuning?

    /// The bundled look values (nil if the file is missing).
    public static let bundled: LookSpec? = try? StyleLibrary.look()
}

extension StyleLibrary {
    /// `Profiles/look.json`.
    public static func look() throws -> LookSpec {
        try JSONDecoder().decode(LookSpec.self, from: data("look"))
    }
}

/// The shared approved-mock values (`Profiles/mock-values.json`, a generated copy of
/// Resources/look/mock-values.json; never hand-edited): "pack/key" → value.
public struct MockValues: Sendable {
    let strings: [String: String]
    let numbers: [String: Double]

    public static let bundled: MockValues? = {
        guard let data = try? StyleLibrary.data("mock-values"),
              let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let entries = json["entries"] as? [String: Any] else { return nil }
        var strings: [String: String] = [:], numbers: [String: Double] = [:]
        for (key, entry) in entries {
            let v = (entry as? [String: Any])?["value"]
            if let s = v as? String { strings[key] = s } else if let n = v as? NSNumber { numbers[key] = n.doubleValue }
        }
        return MockValues(strings: strings, numbers: numbers)
    }()

    public func string(_ key: String) -> String? { strings[key] }
    public func number(_ key: String) -> Double? { numbers[key] }
}
