import {registerHooks} from 'node:module';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
import test from 'node:test';import assert from 'node:assert/strict';
registerHooks({resolve(s,c,next){if(s==='three'||s==='three/webgpu')s=pathToFileURL(resolve('web/node_modules/three/build/three.webgpu.js')).href;return next(s,c);}});
const T=await import('three/webgpu'),{farEligible,installFarParent}=await import('../spatial-far.js'),{geometryFingerprint}=await import('../spatial-cells.js');
const b=new T.Box3(new T.Vector3(-10,0,-10),new T.Vector3(10,10,10)),camera=new T.PerspectiveCamera(50,1,.1,5000);
function eligible(y){camera.position.set(0,y,0);camera.lookAt(0,0,0);camera.updateMatrixWorld();return farEligible(b,camera.position,camera.matrixWorldInverse,.1);}
test('complete actual bounds retain exact near and admit only >=400 m',()=>{assert.equal(eligible(40),false);assert.equal(eligible(150),false);assert.equal(eligible(409),false);assert.equal(eligible(410),true);assert.equal(eligible(600),true);});
test('parent crossing eye/near plane always retains children',()=>{camera.position.set(0,600,0);camera.lookAt(0,1000,0);camera.updateMatrixWorld();assert.equal(farEligible(b,camera.position,camera.matrixWorldInverse,.1),false);});
test('atomic far/child swap restores children and leaves original geometry alive',()=>{const scene=new T.Scene(),root=new T.Group(),g=new T.BoxGeometry(20,10,20),material=new T.MeshBasicMaterial(),o=new T.Mesh(g,material);root.add(o);scene.add(root);const fg=g.clone(),s={sources:[geometryFingerprint(g)],bounds:[-10,-5,-10,10,5,10],rows:[],geometryFingerprint:geometryFingerprint(fg)},world={root,materials:{static:material}},v=installFarParent(scene,camera,world,{sidecar:s,geometry:fg},{features:new WeakMap(),spatialSidecar:{geometries:{}}});camera.position.set(0,600,0);camera.lookAt(0,0,0);v.update();assert.equal(v.parent.visible,true);assert.equal(o.visible,false);assert.equal(o.geometry,g);assert.equal(o.userData.farShadowVisible,true);camera.position.set(0,150,0);camera.lookAt(0,0,0);v.update();assert.equal(v.parent.visible,false);assert.equal(o.visible,true);assert.equal(v.report.swaps,2);});
test('missing source fails closed before any original visibility changes',()=>{const scene=new T.Scene(),root=new T.Group();scene.add(root);assert.throws(()=>installFarParent(scene,camera,{root,materials:{static:{}}},{sidecar:{sources:['missing']},geometry:new T.BoxGeometry()},{spatialSidecar:{geometries:{}}}),/coverage mismatch/);});
test('a wide or tall complete parent prevents a premature partial swap',()=>{const wide=new T.Box3(new T.Vector3(-1000,0,-1000),new T.Vector3(1000,300,1000));camera.position.set(0,600,0);camera.lookAt(0,0,0);camera.updateMatrixWorld();assert.equal(farEligible(wide,camera.position,camera.matrixWorldInverse,.1),false);});

test('off-screen crossing does not disqualify visible changed bounds',()=>{camera.position.set(0,600,0);camera.lookAt(-600,0,0);camera.near=150;camera.updateProjectionMatrix();camera.updateMatrixWorld();const core=new T.Box3(new T.Vector3(-510,0,-510),new T.Vector3(510,25,510)),front=new T.Box3(new T.Vector3(-200,0,-20),new T.Vector3(-180,20,20)),behind=new T.Box3(new T.Vector3(390,0,-20),new T.Vector3(420,20,20));assert.equal(farEligible(core,camera.position,camera.matrixWorldInverse,150),false);assert.equal(farEligible(core,camera.position,camera.matrixWorldInverse,150,400,[front,behind],camera.projectionMatrix),true);});
test('a changed feature crossing the visible near plane blocks the whole atomic swap',()=>{camera.position.set(0,600,0);camera.lookAt(0,0,0);camera.near=590;camera.updateProjectionMatrix();camera.updateMatrixWorld();const core=new T.Box3(new T.Vector3(-500,0,-500),new T.Vector3(500,20,500)),cross=new T.Box3(new T.Vector3(-10,0,-10),new T.Vector3(10,20,10));assert.equal(farEligible(core,camera.position,camera.matrixWorldInverse,590,400,[cross],camera.projectionMatrix),false);});
