// visual-v2 §8.1 is the filed common contract. owner-log names tiers but gives
// no separate numeric allocations. Do not promote web-stack-v1 research to a decision.
export const phoneBudget={mainTriangles:400000,shadowTriangles:150000,mainDraws:100,textureMiB:null,tiers:{hero:'15 Pro+',standard:'14–15',floor:'12–13'},tierAllocations:'R: floor uses shared limits; hero/standard and texture budgets not filed'};
export function installCostLedger(renderer,camera){
 const backend=renderer.backend,gl=backend.gl,textures=new Map(),buffers=new Map();let buckets={},boundBuffer;
 const formats=new Map(['R8:1','RG8:2','RGB8:3','RGBA8:4','SRGB8_ALPHA8:4','R16F:2','RG16F:4','RGBA16F:8','R32F:4','RG32F:8','RGBA32F:16','DEPTH_COMPONENT16:2','DEPTH_COMPONENT24:4','DEPTH_COMPONENT32F:4','DEPTH24_STENCIL8:4','DEPTH32F_STENCIL8:8'].map(s=>{const [k,n]=s.split(':');return [gl[k],{name:k,bytes:+n}];}));
 const create=backend.createTexture.bind(backend),destroy=backend.destroyTexture.bind(backend);
 backend.createTexture=(t,o)=>{create(t,o);const format=formats.get(backend.get(t).glInternalFormat);let pixels=0;for(let l=0;l<o.levels;l++)pixels+=Math.max(1,o.width>>l)*Math.max(1,o.height>>l)*(o.depth||1)*(t.isCubeTexture?6:1);textures.set(t,{name:t.name||'renderer resource',width:o.width,height:o.height,levels:o.levels,format:format?.name||'unknown',bytes:format?pixels*format.bytes:null,target:!!(t.isRenderTargetTexture||t.isDepthTexture)});};
 backend.destroyTexture=t=>{textures.delete(t);return destroy(t);};
 const bind=gl.bindRenderbuffer.bind(gl);gl.bindRenderbuffer=(target,b)=>{boundBuffer=b;return bind(target,b);};
 for(const name of ['renderbufferStorage','renderbufferStorageMultisample']){const original=gl[name].bind(gl);gl[name]=(...a)=>{const multi=name.endsWith('Multisample'),samples=multi?a[1]:1,format=formats.get(a[multi?2:1]),width=a[multi?3:2],height=a[multi?4:3];buffers.set(boundBuffer,{name:'renderbuffer',width,height,samples,format:format?.name||'unknown',bytes:format?width*height*samples*format.bytes:null});return original(...a);};}
 const del=gl.deleteRenderbuffer.bind(gl);gl.deleteRenderbuffer=b=>{buffers.delete(b);return del(b);};
 const draw=backend.draw.bind(backend);backend.draw=(object,info)=>{const d=info.render.drawCalls,t=info.render.triangles;draw(object,info);const phase=object.camera===camera?'main':object.camera.isOrthographicCamera&&object.object.userData.costCategory?'shadow':'post';const category=object.object.userData.costCategory||'sky/composite',key=phase+'/'+category,b=buckets[key]||={draws:0,triangles:0};b.draws+=info.render.drawCalls-d;b.triangles+=info.render.triangles-t;};
 return {reset(){buckets={};},snapshot(){const allocated=[...textures.values()],targets=[...buffers.values()],sum=a=>a.reduce((s,v)=>s+(v.bytes||0),0)/1048576;return {budget:phoneBudget,passes:structuredClone(buckets),textures:allocated,renderbuffers:targets,contentTextureMiB:sum(allocated.filter(t=>!t.target)),targetTextureMiB:sum(allocated.filter(t=>t.target)),renderbufferMiB:sum(targets),unknownAllocations:[...allocated,...targets].filter(t=>t.bytes===null).length,excludes:'default framebuffer, driver padding, CPU copies; allocation ledger not process memory',gpuMilliseconds:'unmeasured; desktop frame intervals are not per-effect or phone GPU time'};}};
}
