import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three/webgpu';
import {installFarTrial} from './candidate-far-runtime.js';import {geometryFingerprint,describeRows,SCHEMA} from './spatial-cells.js';
test('outside-core near camera is restored; descent restores exact source and ascent selects only far parent',()=>{
 const scene=new T.Scene(),root=new T.Group(),material=new T.MeshBasicNodeMaterial(),g=new T.BoxGeometry(),source=new T.Mesh(g,material);root.add(source);scene.add(root);
 const camera=new T.PerspectiveCamera(50,1,.1,20000);camera.position.set(10000,40,0);camera.lookAt(0,0,0);camera.updateMatrixWorld();
 const parent=g.clone(),feature=new T.Uint32BufferAttribute(new Uint32Array(parent.attributes.position.count),1);parent.setAttribute('_feature',feature);const bounds=[-.5,-.5,-.5,.5,.5,.5],sidecar={sources:[geometryFingerprint(g)],geometryFingerprint:geometryFingerprint(parent),rows:describeRows(new T.Mesh(parent),feature),bounds,changedBounds:[bounds],minimumDistanceMetres:400,geometryErrorMetres:1,parentScope:'synthetic complete core'};
 const far=installFarTrial(scene,camera,{root,materials:{static:material}},{sidecar,geometry:parent},{features:new WeakMap(),spatialSidecar:{schema:SCHEMA,geometries:{}},groundCeiling:0});assert.equal(far.report.selected,false);assert.equal(source.visible,true);assert.equal(source.geometry,g);assert.equal(far.parent.visible,false);assert.equal(source.userData.farShadowVisible,undefined);
 camera.position.set(0,600,0);camera.lookAt(0,0,0);camera.updateMatrixWorld();far.update();assert.equal(far.report.selected,true);assert.equal(source.visible,false);assert.equal(source.userData.farShadowVisible,true);assert.equal(far.parent.castShadow,false);
 const bytes=Array.from(g.index.array);camera.position.y=150;camera.updateMatrixWorld();far.update();assert.equal(far.report.selected,false);assert.equal(source.visible,true);assert.equal(source.userData.farShadowVisible,undefined);assert.deepEqual(Array.from(source.geometry.index.array),bytes);
 camera.position.y=600;camera.updateMatrixWorld();far.update();assert.equal(far.report.selected,true);
});
test('near/far ring transition restores original resources and source order without duplicate coverage',async()=>{
 const {installContextRing}=await import('./context-ring.js'),camera=new T.PerspectiveCamera(50,1,.1,2000);camera.position.set(0,150,20);camera.lookAt(0,0,0);camera.updateMatrixWorld();
 const core=[-1,-1,1,1],coverage=[-3,-3,3,3],blank={position:[],paint:[],index:[]},land={position:[-3,0,-3,-2,0,-3,-2,0,-2,2,0,2,3,0,2,3,0,3],paint:Array(6).fill([0,1,0,0]).flat(),index:[0,1,2,3,4,5]};
 const data={formatVersion:2,status:'available',area:'synthetic',origin:{latitude:0,longitude:0},core,coverage,fadeWidthM:1,namedSlots:{residential:0,backdrop:1},palette:['#888888','#888888'],cells:[{mesh:land}],water:blank,buildingMasses:[]};
 const b={camera,world:{manifest:{frame:{origin:data.origin}},palettes:{slots:[]},paletteTexture:{image:{data:[]}},materials:{water:new T.MeshBasicMaterial()},root:new T.Group()},policy:{look:{materials:{roughness:{masonry:1},groundBaseHex:{}}}},scene:new T.Scene()};
 const ring=installContextRing(b,data,{mergeOpaque:true,mergeAllowed:()=>camera.position.y>=400}),originals=[...ring.meshes],geometry=originals.map(m=>m.geometry),order=originals.map(m=>m.id);assert.equal(ring.report.uploadedDraws,2);
 camera.position.y=600;camera.updateMatrixWorld();ring.update();assert.equal(ring.report.uploadedDraws,1);assert.equal(ring.meshes.length,1);assert(originals.every(m=>m.parent===null));
 camera.position.y=150;camera.updateMatrixWorld();ring.update();assert.deepEqual(ring.meshes.map(m=>m.id),order);assert.deepEqual(ring.meshes.map(m=>m.geometry),geometry);assert.equal(b.scene.children.filter(m=>m.userData.contextRing).length,2);
 camera.position.y=600;camera.updateMatrixWorld();ring.update();assert.equal(b.scene.children.filter(m=>m.userData.contextRing).length,1);
});
test('far-hidden original rigid caster still submits its complete selected geometry',async()=>{
 const {installShadowCells}=await import('./shadow-cells.js'),scene=new T.Scene(),camera=new T.PerspectiveCamera(),sun=new T.DirectionalLight();sun.castShadow=true;sun.position.set(0,0,20);scene.add(sun,sun.target);const root=new T.Group(),source=new T.Mesh(new T.BoxGeometry(),new T.MeshBasicNodeMaterial());source.castShadow=true;source.visible=false;source.userData.farShadowVisible=true;root.add(source);scene.add(root);
 const shadows=installShadowCells(scene,camera,{root});shadows.update();assert.equal(shadows.report.triangles,12);assert.equal(shadows.report.draws,1);assert.equal(source.visible,false);root.visible=false;shadows.update();assert.equal(shadows.report.triangles,0);
});
test('existing bakeoff material replacement and per-feature wall colours transfer without recolouring originals',()=>{
 const scene=new T.Scene(),root=new T.Group(),legacy=new T.MeshBasicNodeMaterial(),actual=new T.MeshBasicNodeMaterial(),g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute([0,0,0,1,0,0,0,1,0,2,0,0,3,0,0,2,1,0],3));g.setIndex([0,1,2,3,4,5]);g.setAttribute('_paint',new T.Float32BufferAttribute(Array(6).fill([1,1,0,0]).flat(),4));const face=[.1,.2,.3,1,.1,.2,.3,1,.1,.2,.3,1,.8,.7,.6,1,.8,.7,.6,1,.8,.7,.6,1];g.setAttribute('_facade',new T.Float32BufferAttribute(face,4));const inputFeature=new T.Uint32BufferAttribute([10,10,10,20,20,20],1),source=new T.Mesh(g,actual);source.userData.costCategory='opaque world';root.add(source);scene.add(root);
 const parent=g.clone();parent.deleteAttribute('_facade');const farFeature=new T.Uint32BufferAttribute([0,0,0,1,1,1],1);parent.setAttribute('_feature',farFeature);const s={sources:[geometryFingerprint(g)],geometryFingerprint:geometryFingerprint(parent),rows:describeRows(new T.Mesh(parent),farFeature),bounds:[0,0,0,3,1,0],changedBounds:[[0,0,0,1,1,0],[2,0,0,3,1,0]],minimumDistanceMetres:400,geometryErrorMetres:1,parentScope:'synthetic complete core'},camera=new T.PerspectiveCamera(50,1,.1,2000);camera.position.set(0,600,0);camera.lookAt(0,0,0);camera.updateMatrixWorld();const world={root,materials:{static:legacy}},before=Array.from(g.attributes._facade.array);
 const far=installFarTrial(scene,camera,world,{sidecar:s,geometry:parent},{features:new WeakMap([[g,inputFeature]]),spatialSidecar:{schema:SCHEMA,geometries:{}},groundCeiling:40});assert.equal(far.report.selected,true);assert.equal(far.parent.material,actual);assert.equal(world.materials.static,legacy);assert.deepEqual(Array.from(parent.attributes._facade.array),before);assert.deepEqual(Array.from(g.attributes._facade.array),before);assert.equal(far.report.surfaceTransfer.copiedVertices,6);
});
test('identical local chunk geometry retains distinct feature overrides in manifest order',async()=>{
 const {transferExistingFacades}=await import('./candidate-far-runtime.js'),g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute([0,0,0,1,0,0,0,1,0],3));g.setIndex([0,1,2]);g.setAttribute('_paint',new T.Float32BufferAttribute(Array(3).fill([1,1,0,0]).flat(),4));g.setAttribute('_facade',new T.Float32BufferAttribute(Array(3).fill([.1,.2,.3,1]).flat(),4));const h=g.clone();h.attributes._facade.array.set(Array(3).fill([.8,.7,.6,1]).flat());const a=new T.Mesh(g),b=new T.Mesh(h),feature=new T.Uint32BufferAttribute([0,0,0],1),parent=new T.BufferGeometry();parent.setAttribute('position',new T.Float32BufferAttribute([...g.attributes.position.array,...h.attributes.position.array],3));parent.setIndex([0,1,2,3,4,5]);parent.setAttribute('_paint',new T.Float32BufferAttribute(Array(6).fill([1,1,0,0]).flat(),4));parent.setAttribute('_feature',new T.Uint32BufferAttribute([0,0,0,1,1,1],1));const fingerprint=geometryFingerprint(g);assert.equal(geometryFingerprint(h),fingerprint);transferExistingFacades({geometry:parent,sidecar:{sources:[fingerprint,fingerprint],rows:[{},{}]}},[a,b],new WeakMap([[g,feature],[h,feature]]));assert.deepEqual(Array.from(parent.attributes._facade.array),[...g.attributes._facade.array,...h.attributes._facade.array]);
});
