import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import * as T from 'three/webgpu';
import {lightTrialMode,lightTrialValues,installLightTrial} from './light-trial.js';
import {witnessLight} from './lighting.js';
const main=await readFile('web/bakeoff/main.js','utf8');
const stripped=main.replace(/ \/\/ SURFACE_ROLES_BEGIN\n[\s\S]*? \/\/ SURFACE_ROLES_END\n/g,'').replace(/ \/\/ LIGHT_TRIAL_BEGIN\n[\s\S]*? \/\/ LIGHT_TRIAL_END\n/g,'').replace('lightTrial,','');
assert.equal(stripped,execFileSync('git',['show','8f08c42:web/bakeoff/main.js'],{encoding:'utf8'}));
assert.equal(lightTrialMode(), 'off');assert.equal(lightTrialMode('off'),'off');assert.equal(lightTrialMode('on'),'on');assert.throws(()=>lightTrialMode('soft'));
const look=JSON.parse(await readFile('docs/proposals/style-b-calibration-v2/values.json')).sharedLook,L=look.lighting;
const scene=new T.Scene(),sun=new T.DirectionalLight(L.sun.hex),fill=new T.HemisphereLight(L.sky.fillHex,L.sky.fillHex,2);scene.add(sun,fill);
const original={sun:sun.toJSON(),upper:fill.color.toArray(),intensity:fill.intensity};
const report=installLightTrial(scene,sun,{look,...witnessLight(L)});
assert.deepEqual(sun.toJSON(),original.sun);assert.deepEqual(fill.color.toArray(),original.upper);assert.equal(fill.intensity,original.intensity);
assert.deepEqual(fill.groundColor.toArray(),original.upper.map(x=>x*.65));assert.equal(scene.children.length,2);assert.equal(report.depthComparisons,16);assert.equal(report.filterWidthPx,2);assert(Math.abs(report.witness.ratio-.62)<1e-12);assert(sun.shadow.filterNode);
assert.deepEqual(lightTrialValues(L).groundScale,.65);
assert.equal(await readFile('web/bakeoff/shadow-casters.js','utf8'),execFileSync('git',['show','8f08c42:web/bakeoff/shadow-casters.js'],{encoding:'utf8'}));
const worker=await readFile('scripts/capture_web.mjs','utf8');assert(worker.includes("mode.lightTrial=values.lightTrial"));assert(worker.includes("lightTrialReport:b.lightTrial??null"));assert(worker.includes("lightTrial did not resolve as requested"));
console.log('PASS light trial: default source identity, mode validation, 0.62 horizontal witness, 2px/16-tap filter, unchanged light strength/reach/map/casters/pass count.');
