import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {resolvePolicy,regionalSpecies} from './policy.js';
const root=process.env.WORLDENGINE_ASSETS||resolve('.');
const get=async p=>JSON.parse(await readFile(p,'utf8'));
const cal=await get(`${root}/docs/proposals/style-b-calibration-v2/values.json`),lake=await get(`${root}/docs/proposals/lake-winter-v1/lake-winter-values.json`),foliage=await get(`${root}/docs/proposals/foliage-seasons-v1/foliage-values.json`),fixture=await get('web/bakeoff/fixture.json');
const correction=await get('web/bakeoff/data/sky-correction.json'),haze=await get('web/bakeoff/data/haze-values.json');
const a=resolvePolicy(cal,lake,fixture,correction,haze,'front-range'),b=resolvePolicy(cal,lake,{...fixture,camera:{fov:3},scene:'unseen-city'},correction,haze,'front-range');
assert.equal(a.sky.zenithHex,correction.set['lighting.sky.zenithHex']);
assert.deepEqual(a,b,'Camera and scene must not influence look policy');
assert.equal(a.look.lighting.exposure.linearGain,cal.sharedLook.lighting.exposure.linearGain);
assert.equal(a.hazeExtinctionPerM,haze.regions.find(r=>r.id==='front-range').seasons.summer.clear.extinctionPerM);
assert.ok(Math.abs(a.witness.ratio-cal.sharedLook.lighting.shadow.neutralWitnessShadowToLitLinearY)<1e-12);
for(const region of ['denver','chicago'])for(const kind of ['treeBroad','treeOval','treeSpreading'])assert.ok(foliage.cities.find(c=>c.id===region).mix.some(m=>m.id===regionalSpecies(foliage,region,kind).id));
console.log('PASS: camera-independent policy, pack ratios, shared haze and regional foliage');
