import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from 'three/webgpu';
import {featureRows,geometryKey,installSceneBudget,validateSceneBudgetQuery} from './scene-budget.js';
const camera=()=>{const c=new T.PerspectiveCamera(50,1,.2,100);c.position.set(0,0,10);c.lookAt(0,0,0);c.updateMatrixWorld();return c;};
function geometry(){const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute([-1,-1,0,1,-1,0,0,1,0,100,-1,0,102,-1,0,101,1,0],3));g.setIndex([0,1,2,3,4,5]);return g;}
test('explicit OFF-only query rejects combinations',()=>{validateSceneBudgetQuery(new URLSearchParams('sceneBudget=1'));for(const q of ['sceneBudget=0','sceneBudget=1&crownV3=standard','sceneBudget=1&crownV2=floor','sceneBudget=1&foliageExp1=layered','sceneBudget=1&baseline'])assert.throws(()=>validateSceneBudgetQuery(new URLSearchParams(q)));});
test('feature bounds contain every triangle vertex',()=>{const m=new T.Mesh(geometry()),rows=featureRows(m,new T.Float32BufferAttribute([0,0,0,1,1,1],1));assert.equal(rows.length,2);assert.deepEqual(rows[0].indices,[0,1,2]);assert.equal(rows[1].bounds.min.x,100);});
test('main feature selection does not alter shadow proxies and returns after camera move',()=>{const scene=new T.Scene(),c=camera(),g=geometry(),m=new T.Mesh(g,new T.MeshBasicMaterial());m.userData.costCategory='opaque world';scene.add(m);const shadow=new T.Mesh(g,m.material);shadow.layers.set(1);shadow.castShadow=true;scene.add(shadow);const features=new WeakMap([[g,new T.Float32BufferAttribute([0,0,0,1,1,1],1)]]),v=installSceneBudget(scene,c,features);assert.equal(v.report.retainedTriangles,1);assert.equal(v.report.rejectedTriangles,1);assert.equal(shadow.layers.mask,2);assert.equal(shadow.castShadow,true);assert.deepEqual(Array.from(g.index.array),[0,1,2,3,4,5]);c.position.x=101;c.lookAt(101,0,0);c.updateMatrixWorld();v.update();assert.equal(v.report.retainedTriangles,1);assert.equal(v.report.updates,2);v.update();assert.equal(v.report.updates,2);});
test('compatible instances pool while preserving each matrix and tint',()=>{const scene=new T.Scene(),c=camera(),material=new T.MeshBasicMaterial(),g=new T.PlaneGeometry(1,1);for(const [x,tint]of [[-1,.25],[1,.75]]){const local=g.clone();local.setAttribute('leafTint',new T.InstancedBufferAttribute(new Float32Array([tint,0,0]),3));const m=new T.InstancedMesh(local,material,1);m.setMatrixAt(0,new T.Matrix4().makeTranslation(x,0,0));scene.add(m);}const v=installSceneBudget(scene,c);assert.equal(v.report.pooledDraws,1);const pooled=scene.children.at(-1).children[0];assert.equal(pooled.count,2);assert.deepEqual(Array.from(pooled.geometry.attributes.leafTint.array.slice(0,6)),[.25,0,0,.75,0,0]);const m=new T.Matrix4();pooled.getMatrixAt(1,m);assert.equal(m.elements[12],1);});
test('different topology/materials never pool and geometry identity includes normals',()=>{const a=new T.PlaneGeometry(1,1),b=a.clone();b.attributes.normal.setXYZ(0,1,0,0);assert.notEqual(geometryKey(a),geometryKey(b));const scene=new T.Scene(),c=camera();for(const g of [a,b])scene.add(new T.InstancedMesh(g,new T.MeshBasicMaterial(),1));const v=installSceneBudget(scene,c);assert.equal(v.report.pooledDraws,2);});

test('default entry imports only shipping main, without experiment hooks',async()=>{const {readFile}=await import('node:fs/promises'),source=await readFile(new URL('./entry.js',import.meta.url),'utf8');assert.match(source,/get\('sceneBudget'\)==='1'\?'\.\/scene-budget-entry\.js':'\.\/main\.js'/);assert.equal((source.match(/import\(/g)||[]).length,1);});

test('resize replacement meshes enter selection and removed facade meshes disappear',()=>{const scene=new T.Scene(),c=camera(),m=new T.Mesh(new T.PlaneGeometry(1,1),new T.MeshBasicMaterial());scene.add(m);const v=installSceneBudget(scene,c);assert.equal(v.report.retainedTriangles,2);scene.remove(m);const replacement=new T.Mesh(new T.PlaneGeometry(1,1,2,2),m.material);scene.add(replacement);v.update();assert.equal(v.report.retainedTriangles,8);assert.equal(v.report.mainSourceMeshes,1);assert.equal(scene.children.at(-2).children.length,1);});
