import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three/webgpu';
import {windEnvelope,fpTransformBox,rigidIntersects,needsUnboundedPadding,installShadowCells} from './shadow-cells.js';
test('highp interval encloses separated Float32 and fused-affine corner transforms',()=>{const box=new T.Box3(new T.Vector3(-800,-3,-400),new T.Vector3(900,30,600)),m=new T.Matrix4().makeRotationY(.31);m.setPosition(432.1,-50.2,17.9);const interval=fpTransformBox(box,m),e=m.elements.map(Math.fround);for(const x of [box.min.x,box.max.x])for(const y of [box.min.y,box.max.y])for(const z of [box.min.z,box.max.z]){const v=[x,y,z,1],a=[];for(let r=0;r<3;r++){let s=0;for(let k=0;k<4;k++)s=Math.fround(s+Math.fround(e[k*4+r]*v[k]));a.push(s);}assert.ok(interval.containsPoint(new T.Vector3(...a)));assert.ok(interval.containsPoint(new T.Vector3(x,y,z).applyMatrix4(m)));}});
test('edge touching caster remains; fully clipped caster is rejected; nonfinite fails closed',()=>{const c=new T.OrthographicCamera(-40,40,40,-40,1,400),eye=new T.Matrix4().makeTranslation(0,0,-10),box=new T.Box3(new T.Vector3(40,0,0),new T.Vector3(41,1,1));assert.equal(rigidIntersects(box,null,eye,c.projectionMatrix),true);assert.equal(rigidIntersects(box.clone().translate(new T.Vector3(10,0,0)),null,eye,c.projectionMatrix),false);box.max.x=Infinity;assert.equal(rigidIntersects(box,null,eye,c.projectionMatrix),true);});
test('unknown deformation retains source; known positive-sway graph has finite bounds',()=>{const g=new T.BoxGeometry(),m=new T.MeshBasicNodeMaterial(),o=new T.Mesh(g,m);assert.equal(needsUnboundedPadding(o),false);m.positionNode={isNode:true};assert.equal(needsUnboundedPadding(o),true);g.setAttribute('_paint',new T.Float32BufferAttribute(new Float32Array(g.attributes.position.count*4),4));const world={materials:{foliage:m}};assert.equal(needsUnboundedPadding(o,world),false);g.attributes._paint.setW(0,1);assert.equal(needsUnboundedPadding(o,world),false);});
test('original casters/main remain alive; no reach or LOD changes; source instances keep capacity',()=>{const scene=new T.Scene(),camera=new T.PerspectiveCamera(),sun=new T.DirectionalLight();sun.castShadow=true;sun.position.set(0,0,20);scene.add(sun,sun.target);const g=new T.BoxGeometry(1,1,1),m=new T.MeshBasicNodeMaterial(),mesh=new T.InstancedMesh(g,m,1001);mesh.castShadow=true;mesh.count=2;mesh.setMatrixAt(0,new T.Matrix4());mesh.setMatrixAt(1,new T.Matrix4().makeTranslation(1000,0,0));scene.add(mesh);const before=sun.shadow.camera.projectionMatrix.clone(),s=installShadowCells(scene,camera,{root:scene});s.update();assert.deepEqual(sun.shadow.camera.projectionMatrix.elements,before.elements);assert.equal(mesh.count,2);assert.equal(mesh.layers.test(camera.layers),true);assert.equal(s.root.children[0].instanceMatrix.count,1001);assert.equal(s.root.children[0].count,1);assert.equal(s.report.reachChanged,false);assert.equal(s.report.lodChanged,false);});
test('static caster proxy retains original primitive order and complete feature geometry',()=>{const scene=new T.Scene(),camera=new T.PerspectiveCamera(),sun=new T.DirectionalLight();sun.castShadow=true;sun.position.set(0,0,20);scene.add(sun,sun.target);const g=new T.BoxGeometry(1,1,1),mesh=new T.Mesh(g,new T.MeshBasicNodeMaterial());mesh.castShadow=true;scene.add(mesh);const indices=Array.from(g.index.array),s=installShadowCells(scene,camera,{root:scene});s.update();assert.equal(s.root.children.length,1);const proxy=s.root.children[0];assert.equal(proxy.isMesh,true);assert.deepEqual(Array.from(proxy.geometry.index.array).slice(0,proxy.geometry.drawRange.count),indices);assert.equal(mesh.geometry,g);});
test('shared non-leading vertices cannot overwrite a complete feature selection',()=>{const scene=new T.Scene(),camera=new T.PerspectiveCamera(),sun=new T.DirectionalLight();sun.castShadow=true;sun.position.set(0,0,20);scene.add(sun,sun.target);const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute([1000,0,0,0,0,0,1,1,0,2000,0,0,2001,1,0],3));g.setIndex([0,1,2,3,0,4]);const mesh=new T.Mesh(g,new T.MeshBasicNodeMaterial());mesh.castShadow=true;scene.add(mesh);const features=new WeakMap([[g,new T.Float32BufferAttribute([10,10,10,20,20],1)]]),s=installShadowCells(scene,camera,{root:scene},{features});s.update();assert.equal(s.root.children[0].geometry.drawRange.count,3);assert.deepEqual(Array.from(s.root.children[0].geometry.index.array).slice(0,3),[0,1,2]);});
test('uncomputed proxy geometry bounds stay null for renderer lazy initialization',()=>{const scene=new T.Scene(),camera=new T.PerspectiveCamera(),sun=new T.DirectionalLight();sun.castShadow=true;sun.position.set(0,0,20);scene.add(sun,sun.target);const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute([0,0,0,1,0,0,0,1,0],3));g.setIndex([0,1,2]);const mesh=new T.Mesh(g,new T.MeshBasicNodeMaterial());mesh.castShadow=true;mesh.frustumCulled=false;scene.add(mesh);const s=installShadowCells(scene,camera,{root:scene});s.update();assert.equal(s.root.children[0].geometry.boundingSphere,null);assert.equal(s.root.children[0].geometry.boundingBox,null);});

test('wind envelope uses post-instance height and bounds every phase at positive and negative heights',()=>{const box=new T.Box3(new T.Vector3(-1,-4,-1),new T.Vector3(1,10,1)),instance=new T.Matrix4().makeScale(2,3,2);instance.setPosition(0,-50,0);const bound=windEnvelope(box,instance,2);for(const y of [-4,10])for(let phase=0;phase<64;phase++){const v=new T.Vector3(1,y,-1).applyMatrix4(instance),amp=Math.fround(.0025)*2*v.y;v.x+=Math.sin(phase)*amp;v.z+=Math.cos(phase)*amp;assert.ok(bound.containsPoint(v));}assert.ok(bound.min.x<-2-.31);assert.deepEqual(windEnvelope(box,null,0),box);});
test('nonfinite known wind weights fail closed rather than making a clipping decision',()=>{const g=new T.BoxGeometry(),m=new T.MeshBasicNodeMaterial(),o=new T.Mesh(g,m);m.positionNode={isNode:true};g.setAttribute('_paint',new T.Float32BufferAttribute(new Float32Array(g.attributes.position.count*4),4));g.attributes._paint.setW(0,NaN);assert.equal(needsUnboundedPadding(o,{materials:{foliage:m}}),true);});
test('insufficient vertex highp precision retains the complete source',()=>{const scene=new T.Scene(),camera=new T.PerspectiveCamera(),sun=new T.DirectionalLight();sun.castShadow=true;sun.position.set(0,0,20);scene.add(sun,sun.target);const g=new T.BoxGeometry(),o=new T.InstancedMesh(g,new T.MeshBasicNodeMaterial(),2);o.castShadow=true;o.setMatrixAt(0,new T.Matrix4());o.setMatrixAt(1,new T.Matrix4().makeTranslation(1000,0,0));scene.add(o);const gl={VERTEX_SHADER:1,HIGH_FLOAT:2,getShaderPrecisionFormat:()=>({precision:16})},v=installShadowCells(scene,camera,{root:scene},{renderer:{backend:{gl}}});v.update();assert.equal(v.root.children.length,0);assert.equal(v.report.unboundedTriangles,g.index.count/3*2);});
