import Foundation
import simd
import WorldGeo
import WorldMap

enum Stats {
    static func length(_ line: [LocalPoint]) -> Double {
        zip(line, line.dropFirst()).reduce(0) { $0 + simd_distance($1.0, $1.1) }
    }

    static func km(_ m: Double) -> String { String(format: "%.2f km", m / 1000) }

    static func table(_ rows: [(String, String)], header: (String, String)) -> String {
        var s = "| \(header.0) | \(header.1) |\n|---|---:|\n"
        for r in rows { s += "| \(r.0) | \(r.1) |\n" }
        return s
    }

    /// Street-level data inventory for an area (Markdown).
    static func markdown(for dir: URL) throws -> String {
        let manifest = try AreaLoader.loadManifest(dir)
        let f = try AreaLoader.loadFeatures(dir)
        let src = manifest.sources.first
        var md = "# Street-level data inventory: \(manifest.name)\n\n"
        md += "Generated by `worldbake stats` from `\(src?.path ?? "?")` (OSM data timestamp \(src?.dataTimestamp ?? "?")). "
        md += String(format: "Area %.0f × %.0f m around (%.4f, %.4f).\n\n", manifest.widthMeters, manifest.heightMeters,
                     manifest.center.latitude, manifest.center.longitude)

        // Buildings
        let b = f.buildings.filter { !$0.isPart }
        let withHeight = b.filter(\.hasHeightTag).count
        let withLevels = b.filter(\.hasLevelsTag).count
        let withRoofShape = b.filter { $0.roofShape != nil }.count
        func pct(_ n: Int, _ d: Int) -> String { d == 0 ? "0" : String(format: "%d (%.0f%%)", n, 100.0 * Double(n) / Double(d)) }
        md += "## Buildings\n\n"
        md += table([
            ("Buildings (excluding parts)", "\(b.count)"),
            ("`building:part` features", "\(f.buildings.count - b.count)"),
            ("with `height`", pct(withHeight, b.count)),
            ("with `building:levels`", pct(withLevels, b.count)),
            ("with `roof:shape`", pct(withRoofShape, b.count)),
            ("with `roof:colour` / `building:colour`", "\(b.filter { $0.tags["roof:colour"] != nil }.count) / \(b.filter { $0.tags["building:colour"] != nil }.count)"),
            ("with `building:material`", "\(b.filter { $0.tags["building:material"] != nil }.count)"),
            ("with an address (`addr:housenumber`)", pct(b.filter { $0.tags["addr:housenumber"] != nil }.count, b.count)),
        ], header: ("Measure", "Count"))

        md += "\n### Building types (`building=*`)\n\n| Type | Count | with levels | median footprint |\n|---|---:|---:|---:|\n"
        for (type, group) in Dictionary(grouping: b, by: \.type).sorted(by: { $0.value.count > $1.value.count }) {
            let areas = group.map(\.footprint.area).sorted()
            md += String(format: "| `%@` | %d | %d | %.0f m² |\n", type, group.count, group.filter(\.hasLevelsTag).count, areas[areas.count / 2])
        }

        let levelValues = Dictionary(grouping: b.compactMap(\.levels), by: { $0 }).mapValues(\.count)
        md += "\n### `building:levels` values\n\n"
        md += levelValues.isEmpty ? "None.\n" : levelValues.sorted { $0.key < $1.key }.map { String(format: "%g: %d", $0.key, $0.value) }.joined(separator: " · ") + "\n"
        let roofShapes = Dictionary(grouping: b.compactMap(\.roofShape), by: { $0 }).mapValues(\.count)
        md += "\n### `roof:shape` values\n\n"
        md += roofShapes.isEmpty ? "None.\n" : roofShapes.sorted { $0.value > $1.value }.map { "`\($0.key)`: \($0.value)" }.joined(separator: " · ") + "\n"
        let sources = Dictionary(grouping: b, by: \.height.source).mapValues(\.count)
        md += "\nHeight source after fallback rules: " + BuildingHeight.Source.allCases.map { "\($0.rawValue) \(sources[$0] ?? 0)" }.joined(separator: " · ") + "\n"

        // Ways
        md += "\n## Roads, paths and sidewalks\n\n| Kind | Ways | Length |\n|---|---:|---:|\n"
        for (kind, group) in Dictionary(grouping: f.roads + f.paths, by: \.kind).sorted(by: { $0.value.count > $1.value.count }) {
            md += "| \(kind.rawValue) | \(group.count) | \(km(group.reduce(0) { $0 + length($1.centerline) })) |\n"
        }
        md += "| **sidewalk (`footway=sidewalk`)** | \(f.sidewalks.count) | \(km(f.sidewalks.reduce(0) { $0 + length($1.centerline) })) |\n"
        md += "| crossings (`footway=crossing`) | \(f.paths.filter(\.isCrossing).count) | |\n"

        let streets = f.roads.filter { [.residential, .livingStreet, .unclassified, .tertiary, .secondary, .primary].contains($0.kind) }
        var sideLen: [SidewalkState: Double] = [:]
        for r in streets {
            let l = length(r.centerline)
            sideLen[r.sidewalkLeft, default: 0] += l
            sideLen[r.sidewalkRight, default: 0] += l
        }
        md += "\n### Sidewalk tags on streets (residential through primary), by street side\n\n"
        md += table([SidewalkState.unknown, .tagged, .separate, .none].map { ($0.rawValue, km(sideLen[$0] ?? 0)) }, header: ("Side state", "Length"))

        // Areas
        md += "\n## Areas\n\n| Kind | Features | Area |\n|---|---:|---:|\n"
        for (kind, group) in Dictionary(grouping: f.areas, by: \.kind).sorted(by: { $0.key.rawValue < $1.key.rawValue }) {
            md += String(format: "| %@ | %d | %.0f m² |\n", kind.rawValue, group.count, group.reduce(0) { $0 + $1.polygon.area })
        }

        // Points and lines
        md += "\n## Street furniture and trees\n\n| Kind | Count |\n|---|---:|\n"
        for kind in PointFeature.Kind.allCases {
            let n = f.points(of: kind).count
            if n > 0 { md += "| \(kind.rawValue) | \(n) |\n" }
        }
        for (kind, group) in Dictionary(grouping: f.lines, by: \.kind).sorted(by: { $0.key.rawValue < $1.key.rawValue }) {
            md += "| \(kind.rawValue) (line) | \(group.count) ways, \(km(group.reduce(0) { $0 + length($1.line) })) |\n"
        }
        let trees = f.points(of: .tree)
        let treeKeys = ["genus", "species", "leaf_type", "leaf_cycle", "height", "circumference", "diameter_crown"]
        md += "\nTree tag coverage: " + treeKeys.map { k in "`\(k)` \(trees.filter { $0.tags[k] != nil }.count)" }.joined(separator: " · ") + "\n"

        md += "\n## Load report\n\n"
        md += "\(f.report.nodeCount) nodes, \(f.report.wayCount) ways, \(f.report.relationCount) relations read; "
        md += "\(f.report.unclassifiedCount) tagged ways/relations not used; \(f.report.skipped.count) skipped"
        md += f.report.skipped.isEmpty ? ".\n" : ":\n\n" + f.report.skipped.map { "- \($0.ref): \($0.reason)" }.joined(separator: "\n") + "\n"
        return md
    }

    /// Size of a buildings-only backdrop ring: buildings in the manifest's box whose centroid is
    /// outside the inner (centered) box.
    static func ring(_ dir: URL, innerWidth: Double, innerHeight: Double) throws -> String {
        let manifest = try AreaLoader.loadManifest(dir)
        // The detailed sources only: the context ring (layer "context") is not part of this box.
        let detailed = manifest.sources.filter { $0.layers != [ContextRing.layer] }
        let doc = try AreaLoader.loadDocument(dir, manifest: manifest, layers: Set(detailed.flatMap(\.layers)))
        let f = MapFeatureBuilder(frame: manifest.frame, bounds: manifest.localBounds).build(doc)
        let inner = Rect2D(centerWidth: innerWidth, height: innerHeight)
        let ring = f.buildings.filter { !$0.isPart && !inner.contains($0.footprint.centroid) }
        let vertices = ring.reduce(0) { $0 + $1.footprint.outer.count + $1.footprint.holes.reduce(0) { $0 + $1.count } }
        let roofTris = ring.reduce(0) { $0 + $1.footprint.outer.count - 2 + $1.footprint.holes.reduce(0) { $0 + $1.count + 2 } }
        let wallTris = vertices * 2
        let raw = detailed.reduce(0) { $0 + ($1.bytes ?? 0) }
        var compressed = 0
        for s in detailed {
            let data = try Data(contentsOf: dir.appendingPathComponent(s.path))
            compressed += try (data as NSData).compressed(using: .zlib).count
        }
        // Compact block format: per building 6 bytes (vertex count, height, flags) + 4 bytes per
        // vertex (int16 east/north in decimeters relative to the area origin).
        let compact = ring.count * 6 + vertices * 4
        let sources = Dictionary(grouping: ring, by: \.height.source).mapValues(\.count)
        return """
        Backdrop ring: \(Int(manifest.widthMeters)) × \(Int(manifest.heightMeters)) m box minus the inner \(Int(innerWidth)) × \(Int(innerHeight)) m area
        Buildings in ring: \(ring.count) (total in box \(f.buildings.filter { !$0.isPart }.count))
        Footprint vertices: \(vertices)
        Raw Overpass JSON (buildings layer, whole box): \(raw) bytes; zlib-compressed \(compressed) bytes
        Compact block format estimate (ring only): \(compact) bytes
        Triangles as simple blocks (walls + flat roofs): \(wallTris + roofTris) (walls \(wallTris), roofs \(roofTris))
        Height sources: heightTag \(sources[.heightTag] ?? 0), levels \(sources[.levels] ?? 0), typeDefault \(sources[.typeDefault] ?? 0)
        """
    }
}
