// Select unmodified fields from approved haze-visibility-v1/values.json.
import {readFileSync, writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const source = new URL('../../docs/proposals/haze-visibility-v1/values.json', import.meta.url);
const bytes = readFileSync(source), pack = JSON.parse(bytes);
const {definition, regions, states, severityOverrides, selection, airlight} = pack;
writeFileSync(new URL('pack-data.mjs', import.meta.url),
  '// Generated by build-data.mjs; haze-visibility-v1 keys preserved, never tune here.\nexport default '+
  JSON.stringify({source:'haze-visibility-v1/values.json',sha256:createHash('sha256').update(bytes).digest('hex'),
    definition,regions,states,severityOverrides,selection,airlight},null,2)+';\n');
