#!/usr/bin/env python3
"""The paint-over colour grade as engine data, generated from ChatGPT's paintover-v1 proposal (read-only input).

  scripts/paintover_data.py          regenerate Sources/WorldGen/Profiles/paintover-grade.json
  scripts/paintover_data.py --check  exit 1 if it is out of date with the proposal

Reads docs/proposals/paintover-v1/paintover-values.json: per frame, the grade relative to the engine's
own output (exposure EV, linear contrast slope about 0.18, saturation factor, warmth percent), in the
pack's order after lighting: exposure, contrast, saturation, warmth, then the tone mapper.

Each lighting-bible state takes the mean grade of the paint-over frames that show it (STATES below);
states with no frame stay neutral until a pack covers them (fog-v1, night-v1). Nothing is copied by
hand: change the proposal, rerun this.
"""
import hashlib
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = "docs/proposals/paintover-v1/paintover-values.json"
OUT = "Sources/WorldGen/Profiles/paintover-grade.json"

# Lighting-bible state (grade.json names; smoke is an "other weather" label) → paint-over frames.
STATES = {
    "morning": ["ordinary-street", "evanston-street"],
    "ordinary-1530": ["ordinary-street", "evanston-street"],
    "midday": ["ordinary-street", "evanston-street"],
    "golden-hour": ["lakeview-street", "v2-06"],
    "light-rain": ["showcase-03"],
    "storm": ["showcase-03"],
    "smoke": ["showcase-06"],
}


def build():
    raw = open(os.path.join(ROOT, SRC), "rb").read()
    d = json.loads(raw)
    frames = {f["id"]: f for f in d["frames"]}

    def mean(ids, key):
        return round(sum(frames[i]["grade"][key] for i in ids) / len(ids), 4)

    states = {}
    for state, ids in STATES.items():
        states[state] = {
            "frames": ids,
            "exposureEV": mean(ids, "relativeExposureEV"),
            "contrast": mean(ids, "contrastSlope"),
            "saturation": mean(ids, "saturationFactor"),
            "warmth": round(mean(ids, "warmthPercent") / 100, 4),
            "shadowStrength": round(sum(frames[i]["shadow"]["strengthPercent"] for i in ids) / len(ids) / 100, 4),
        }
    return {
        "comment": f"GENERATED by scripts/paintover_data.py from {SRC} (read-only). Do not edit: change the proposal and rerun.",
        "source": {"path": SRC, "sha256": hashlib.sha256(raw).hexdigest()},
        "order": d["gradeOrder"],
        "definitions": {k: d["definitions"][k] for k in ("exposureEV", "contrast", "saturation", "warmth", "shadowStrength")},
        "states": states,
    }


def main():
    text = json.dumps(build(), indent=1, ensure_ascii=False) + "\n"
    path = os.path.join(ROOT, OUT)
    if "--check" in sys.argv:
        ok = os.path.exists(path) and open(path, encoding="utf-8").read() == text
        print("paint-over grade data up to date" if ok else f"out of date: {OUT}")
        sys.exit(0 if ok else 1)
    open(path, "w", encoding="utf-8").write(text)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
