#!/usr/bin/env python3
"""The rain pack as engine data, generated from ChatGPT's rain-v1 proposal (read-only input).

  scripts/rainfix_data.py          regenerate Sources/WorldGen/Profiles/rain-bible.json
  scripts/rainfix_data.py --check  exit 1 if it is out of date with the proposal

Reads docs/proposals/rain-v1/rain-values.json: wetness states with per-surface darkening, roughness and
sheen; puddles; rain streaks; lamp streaks. Nothing is copied by hand: change the proposal, rerun this.
"""
import hashlib
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = "docs/proposals/rain-v1/rain-values.json"
OUT = "Sources/WorldGen/Profiles/rain-bible.json"


def build():
    raw = open(os.path.join(ROOT, SRC), "rb").read()
    d = json.loads(raw)
    states = []
    for s in d["states"]:
        states.append({
            "id": s["id"], "wetness": s["wetness01"], "rainIntensity": s["rainIntensity01"],
            "rainCountStreet": s["rainCountStreet"], "rainCountAerial": s["rainCountAerial"],
            "puddleCoverage": s["puddleEligibleCoveragePercent"] / 100,
            "surfaces": {v["surface"]: {"darken": v["darkeningPercent"] / 100, "roughness": v["roughness"],
                                        "sheen": v["sheenStrength"]} for v in s["surfaceValues"]},
        })
    p, r, l = d["puddles"], d["rain"], d["lampStreaks"]
    return {
        "comment": f"GENERATED by scripts/rainfix_data.py from {SRC} (read-only). Do not edit: change the proposal and rerun.",
        "source": {"path": SRC, "sha256": hashlib.sha256(raw).hexdigest()},
        "states": states,
        "puddles": {"roughness": p["roughness"], "skyMixNormal": p["skyMixWeightNormal"],
                    "skyMixGrazing": p["skyMixWeightGrazing"], "maxCoverage": p["maxCoverageEligibleAreaPercent"] / 100,
                    "ripples": p["ripples"]},
        "rain": {k: r[k] for k in ("speedMps", "streakLengthM", "widthCssPx", "opacityLight", "opacitySteady", "opacityHeavy",
                                   "nightOpacity", "distanceFadeM", "maxRainStreaks")} | {"aerial": r["aerial"]},
        "lampStreaks": {k: l[k] for k in ("maxFieldsGlobal", "lengthM", "widthM", "opacityDusk", "opacityNight", "fadeDistanceM")}
        | {"color": "#E7BA79"},
    }


def main():
    text = json.dumps(build(), indent=1, ensure_ascii=False) + "\n"
    path = os.path.join(ROOT, OUT)
    if "--check" in sys.argv:
        ok = os.path.exists(path) and open(path, encoding="utf-8").read() == text
        print("rain bible data up to date" if ok else f"out of date: {OUT}")
        sys.exit(0 if ok else 1)
    open(path, "w", encoding="utf-8").write(text)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
