//  SGP4 orbit propagation, near-earth branch (period under 225 minutes), WGS72 constants.
//
//  Faithful Swift port of the Python reference `Tools/livefeeds/livefeeds/sats/sgp4.py`, which follows the
//  revised SGP4 of Vallado, Crawford, Hujsak and Kelso, "Revisiting Spacetrack Report #3" (AIAA 2006-6753),
//  improved operation mode. Deep-space objects (SDP4) are rejected with `SatelliteError.deepSpace`.
//  Output is the TEME frame, km and km/s. Agreement with the reference is checked against the shared vectors
//  in `Tests/LiveSkyTests/Fixtures/live-sky-vectors.json` (generated by `Tools/livefeeds/livefeeds/vectors.py`).
//  Same constants and the same order of floating-point operations as the reference.

import Foundation

enum SGP4Constants {
    static let twoPi: Double = 2 * Double.pi
    static let x2o3: Double = 2.0 / 3.0
    static let mu: Double = 398600.8
    static let re: Double = 6378.135
    static let xke: Double = 60.0 / (pow(re, 3) / mu).squareRoot()
    static let j2: Double = 0.001082616
    static let j3: Double = -0.00000253881
    static let j4: Double = -0.00000165597
    static let j3oj2: Double = j3 / j2
    static let vkmpersec: Double = re * xke / 60.0
}

/// SGP4 propagator for one element set (near-earth only).
public struct SGP4Propagator: Sendable {
    public let elements: SatelliteElements
    public var epoch: Double { elements.epoch }

    let ecco: Double
    let inclo: Double
    let nodeo: Double
    let argpo: Double
    let mo: Double
    let bstar: Double
    let no: Double
    let con41: Double
    let isimp: Int
    let eta: Double
    let cc1: Double
    let x1mth2: Double
    let cc4: Double
    let cc5: Double
    let mdot: Double
    let argpdot: Double
    let nodedot: Double
    let omgcof: Double
    let xmcof: Double
    let nodecf: Double
    let t2cof: Double
    let xlcof: Double
    let aycof: Double
    let delmo: Double
    let sinmao: Double
    let x7thm1: Double
    let d2: Double
    let d3: Double
    let d4: Double
    let t3cof: Double
    let t4cof: Double
    let t5cof: Double

    public init(elements el: SatelliteElements) throws {
        typealias C = SGP4Constants
        let J2 = C.j2
        let J4 = C.j4
        let J3OJ2 = C.j3oj2
        let XKE = C.xke
        let X2O3 = C.x2o3
        let RE = C.re
        let d2r = Double.pi / 180
        let ecco = el.eccentricity
        let inclo = el.inclinationDeg * d2r
        let nodeo = el.raanDeg * d2r
        let argpo = el.argPerigeeDeg * d2r
        let mo = el.meanAnomalyDeg * d2r
        let noKozai = el.meanMotionRevPerDay * C.twoPi / 1440.0
        let bstar = el.bstar
        if !(0 <= ecco && ecco < 1) {
            throw SatelliteError.propagation("eccentricity out of range")
        }
        // initl: un-Kozai the mean motion.
        let eccsq = ecco * ecco
        let omeosq = 1 - eccsq
        let rteosq = omeosq.squareRoot()
        let cosio = cos(inclo)
        let cosio2 = cosio * cosio
        let ak = pow(XKE / noKozai, X2O3)
        let d1 = 0.75 * J2 * (3 * cosio2 - 1) / (rteosq * omeosq)
        var dl = d1 / (ak * ak)
        let adelInner: Double = 1.0 / 3.0 + 134 * dl * dl / 81.0
        let adel = ak * (1 - dl * dl - dl * adelInner)
        dl = d1 / (adel * adel)
        let no = noKozai / (1 + dl)
        let ao = pow(XKE / no, X2O3)
        let sinio = sin(inclo)
        let po = ao * omeosq
        let con42 = 1 - 5 * cosio2
        let con41 = -con42 - cosio2 - cosio2
        let posq = po * po
        let rp = ao * (1 - ecco)
        if C.twoPi / no >= 225.0 {
            let minutes = C.twoPi / no
            throw SatelliteError.deepSpace(
                "period of \(String(format: "%.0f", minutes)) min needs SDP4 (deep space), not supported")
        }
        let ss = 78.0 / RE + 1
        let qzms2t = pow((120.0 - 78.0) / RE, 4)
        let isimp = rp < (220.0 / RE + 1) ? 1 : 0
        var sfour = ss
        var qzms24 = qzms2t
        let perige = (rp - 1) * RE
        if perige < 156 {
            sfour = perige - 78
            if perige < 98 {
                sfour = 20
            }
            qzms24 = pow((120 - sfour) / RE, 4)
            sfour = sfour / RE + 1
        }
        let pinvsq = 1 / posq
        let tsi = 1 / (ao - sfour)
        let eta = ao * ecco * tsi
        let etasq = eta * eta
        let eeta = ecco * eta
        let psisq = abs(1 - etasq)
        let coef = qzms24 * pow(tsi, 4)
        let coef1 = coef / pow(psisq, 3.5)
        let cc2a: Double = ao * (1 + 1.5 * etasq + eeta * (4 + etasq))
        let cc2b: Double = 0.375 * J2 * tsi / psisq * con41 * (8 + 3 * etasq * (8 + etasq))
        let cc2 = coef1 * no * (cc2a + cc2b)
        let cc1 = bstar * cc2
        var cc3 = 0.0
        if ecco > 1e-4 {
            cc3 = -2 * coef * tsi * J3OJ2 * no * sinio / ecco
        }
        let x1mth2 = 1 - cosio2
        let cc4a: Double = eta * (2 + 0.5 * etasq) + ecco * (0.5 + 2 * etasq)
        let cc4b: Double = -3 * con41 * (1 - 2 * eeta + etasq * (1.5 - 0.5 * eeta))
        let cc4c: Double = 0.75 * x1mth2 * (2 * etasq - eeta * (1 + etasq)) * cos(2 * argpo)
        let cc4d: Double = J2 * tsi / (ao * psisq) * (cc4b + cc4c)
        let cc4 = 2 * no * coef1 * ao * omeosq * (cc4a - cc4d)
        let cc5 = 2 * coef1 * ao * omeosq * (1 + 2.75 * (etasq + eeta) + eeta * etasq)
        let cosio4 = cosio2 * cosio2
        let temp1 = 1.5 * J2 * pinvsq * no
        let temp2 = 0.5 * temp1 * J2 * pinvsq
        let temp3 = -0.46875 * J4 * pinvsq * pinvsq * no
        let mdotA: Double = no + 0.5 * temp1 * rteosq * con41
        let mdot = mdotA + 0.0625 * temp2 * rteosq * (13 - 78 * cosio2 + 137 * cosio4)
        let argpdotA: Double = -0.5 * temp1 * con42 + 0.0625 * temp2 * (7 - 114 * cosio2 + 395 * cosio4)
        let argpdot = argpdotA + temp3 * (3 - 36 * cosio2 + 49 * cosio4)
        let xhdot1 = -temp1 * cosio
        let nodedotB: Double = 0.5 * temp2 * (4 - 19 * cosio2) + 2 * temp3 * (3 - 7 * cosio2)
        let nodedot = xhdot1 + nodedotB * cosio
        let omgcof = bstar * cc3 * cos(argpo)
        var xmcof = 0.0
        if ecco > 1e-4 {
            xmcof = -X2O3 * coef * bstar / eeta
        }
        let nodecf = 3.5 * omeosq * xhdot1 * cc1
        let t2cof = 1.5 * cc1
        let den: Double = abs(cosio + 1) > 1.5e-12 ? 1 + cosio : 1.5e-12
        let xlcof = -0.25 * J3OJ2 * sinio * (3 + 5 * cosio) / den
        let aycof = -0.5 * J3OJ2 * sinio
        let delmo = pow(1 + eta * cos(mo), 3)
        let sinmao = sin(mo)
        let x7thm1 = 7 * cosio2 - 1
        var d2 = 0.0
        var d3 = 0.0
        var d4 = 0.0
        var t3cof = 0.0
        var t4cof = 0.0
        var t5cof = 0.0
        if isimp != 1 {
            let cc1sq = cc1 * cc1
            d2 = 4 * ao * tsi * cc1sq
            let temp = d2 * tsi * cc1 / 3
            d3 = (17 * ao + sfour) * temp
            d4 = 0.5 * temp * ao * tsi * (221 * ao + 31 * sfour) * cc1
            t3cof = d2 + 2 * cc1sq
            t4cof = 0.25 * (3 * d3 + cc1 * (12 * d2 + 10 * cc1sq))
            let t5a: Double = 3 * d4 + 12 * cc1 * d3 + 6 * d2 * d2
            t5cof = 0.2 * (t5a + 15 * cc1sq * (2 * d2 + cc1sq))
        }
        self.elements = el
        self.ecco = ecco
        self.inclo = inclo
        self.nodeo = nodeo
        self.argpo = argpo
        self.mo = mo
        self.bstar = bstar
        self.no = no
        self.con41 = con41
        self.isimp = isimp
        self.eta = eta
        self.cc1 = cc1
        self.x1mth2 = x1mth2
        self.cc4 = cc4
        self.cc5 = cc5
        self.mdot = mdot
        self.argpdot = argpdot
        self.nodedot = nodedot
        self.omgcof = omgcof
        self.xmcof = xmcof
        self.nodecf = nodecf
        self.t2cof = t2cof
        self.xlcof = xlcof
        self.aycof = aycof
        self.delmo = delmo
        self.sinmao = sinmao
        self.x7thm1 = x7thm1
        self.d2 = d2
        self.d3 = d3
        self.d4 = d4
        self.t3cof = t3cof
        self.t4cof = t4cof
        self.t5cof = t5cof
    }

    /// (r, v) in TEME, km and km/s, `t` minutes after the element epoch.
    public func propagate(minutesSinceEpoch t: Double) throws -> (r: SatVec3, v: SatVec3) {
        typealias C = SGP4Constants
        let J2 = C.j2
        let XKE = C.xke
        let X2O3 = C.x2o3
        let RE = C.re
        let TWOPI = C.twoPi
        let xmdf = mo + mdot * t
        let argpdf = argpo + argpdot * t
        let nodedf = nodeo + nodedot * t
        var argpm = argpdf
        var mm = xmdf
        let t2 = t * t
        var nodem = nodedf + nodecf * t2
        var tempa = 1 - cc1 * t
        var tempe = bstar * cc4 * t
        var templ = t2cof * t2
        if isimp != 1 {
            let delomg = omgcof * t
            let delm = xmcof * (pow(1 + eta * cos(xmdf), 3) - delmo)
            let temp = delomg + delm
            mm = xmdf + temp
            argpm = argpdf - temp
            let t3 = t2 * t
            let t4 = t3 * t
            tempa = tempa - d2 * t2 - d3 * t3 - d4 * t4
            tempe = tempe + bstar * cc5 * (sin(mm) - sinmao)
            templ = templ + t3cof * t3 + t4 * (t4cof + t * t5cof)
        }
        var nm = no
        var em = ecco
        let inclm = inclo
        if nm <= 0 {
            throw SatelliteError.propagation("mean motion not positive")
        }
        let am = pow(XKE / nm, X2O3) * tempa * tempa
        nm = XKE / pow(am, 1.5)
        em = em - tempe
        if em >= 1 || em < -0.001 {
            throw SatelliteError.propagation("eccentricity out of range during propagation")
        }
        em = max(em, 1e-6)
        mm = mm + no * templ
        var xlm = mm + argpm + nodem
        nodem = fmod(nodem, TWOPI)
        argpm = fmod(argpm, TWOPI)
        xlm = fmod(xlm, TWOPI)
        mm = fmod(xlm - argpm - nodem, TWOPI)
        let sinip = sin(inclm)
        let cosip = cos(inclm)
        let axnl = em * cos(argpm)
        var temp = 1 / (am * (1 - em * em))
        let aynl = em * sin(argpm) + temp * aycof
        let xl = mm + argpm + nodem + temp * xlcof * axnl
        let u = fmod(xl - nodem, TWOPI)
        var eo1 = u
        var tem5 = 9999.9
        var ktr = 1
        while abs(tem5) >= 1e-12 && ktr <= 10 {
            let sineo1 = sin(eo1)
            let coseo1 = cos(eo1)
            tem5 = 1 - coseo1 * axnl - sineo1 * aynl
            tem5 = (u - aynl * coseo1 + axnl * sineo1 - eo1) / tem5
            if abs(tem5) >= 0.95 {
                tem5 = tem5 > 0 ? 0.95 : -0.95
            }
            eo1 += tem5
            ktr += 1
        }
        let sineo1 = sin(eo1)
        let coseo1 = cos(eo1)
        let ecose = axnl * coseo1 + aynl * sineo1
        let esine = axnl * sineo1 - aynl * coseo1
        let el2 = axnl * axnl + aynl * aynl
        let pl = am * (1 - el2)
        if pl < 0 {
            throw SatelliteError.propagation("semi-latus rectum negative")
        }
        let rl = am * (1 - ecose)
        let rdotl = am.squareRoot() * esine / rl
        let rvdotl = pl.squareRoot() / rl
        let betal = (1 - el2).squareRoot()
        temp = esine / (1 + betal)
        let sinu = am / rl * (sineo1 - aynl - axnl * temp)
        let cosu = am / rl * (coseo1 - axnl + aynl * temp)
        var su = atan2(sinu, cosu)
        let sin2u = (cosu + cosu) * sinu
        let cos2u = 1 - 2 * sinu * sinu
        temp = 1 / pl
        let temp1 = 0.5 * J2 * temp
        let temp2 = temp1 * temp
        let mrtA: Double = rl * (1 - 1.5 * temp2 * betal * con41)
        let mrt = mrtA + 0.5 * temp1 * x1mth2 * cos2u
        su = su - 0.25 * temp2 * x7thm1 * sin2u
        let xnode = nodem + 1.5 * temp2 * cosip * sin2u
        let xinc = inclm + 1.5 * temp2 * cosip * sinip * cos2u
        let mvt = rdotl - nm * temp1 * x1mth2 * sin2u / XKE
        let rvdot = rvdotl + nm * temp1 * (x1mth2 * cos2u + 1.5 * con41) / XKE
        let sinsu = sin(su)
        let cossu = cos(su)
        let snod = sin(xnode)
        let cnod = cos(xnode)
        let sini = sin(xinc)
        let cosi = cos(xinc)
        let xmx = -snod * cosi
        let xmy = cnod * cosi
        let ux = xmx * sinsu + cnod * cossu
        let uy = xmy * sinsu + snod * cossu
        let uz = sini * sinsu
        let vx = xmx * cossu - cnod * sinsu
        let vy = xmy * cossu - snod * sinsu
        let vz = sini * cossu
        if mrt < 1 {
            throw SatelliteError.propagation("satellite has decayed")
        }
        let r = SatVec3(mrt * ux * RE, mrt * uy * RE, mrt * uz * RE)
        let v = SatVec3((mvt * ux + rvdot * vx) * C.vkmpersec,
                        (mvt * uy + rvdot * vy) * C.vkmpersec,
                        (mvt * uz + rvdot * vz) * C.vkmpersec)
        return (r: r, v: v)
    }

    /// (r, v) in TEME at a POSIX time (UTC seconds).
    public func propagate(posix: Double) throws -> (r: SatVec3, v: SatVec3) {
        return try propagate(minutesSinceEpoch: (posix - elements.epoch) / 60.0)
    }
}
