// UI regression: real shipped overlay, exact unchanged pixels, credit-only NAIP fixture.
import {createServer} from 'node:http';import {readFile,writeFile,mkdir} from 'node:fs/promises';import {execFileSync} from 'node:child_process';import {createRequire} from 'node:module';import {homedir} from 'node:os';import {resolve} from 'node:path';import assert from 'node:assert/strict';
const req=createRequire(resolve(homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/package.json'));const {chromium}=req('playwright'),{PNG}=req('pngjs');
const out=process.argv[2];if(!out)throw Error('Pass a fresh evidence directory');await mkdir(out,{recursive:false});
const html=await readFile('web/index.html','utf8'),catalog=await readFile('web/credits.json'),current=await readFile('web/credits.js'),old=execFileSync('git',['show','HEAD:web/credits.js']);
const server=createServer((request,response)=>{const u=new URL(request.url,'http://localhost');let data,type='text/javascript';if(u.pathname==='/'){data=html.replace('src="credits.js"',`src="${u.searchParams.get('version')==='old'?'old.js':'credits.js'}"`);type='text/html';}else if(u.pathname==='/credits.js')data=current;else if(u.pathname==='/old.js')data=old;else if(u.pathname==='/credits.json'){data=catalog;type='application/json';}else if(u.pathname==='/app.js')data='';else if(u.pathname.endsWith('/world.json')){data=JSON.stringify(u.pathname.startsWith('/credit/')?{sources:[],credits:[{id:'naip',text:'NAIP imagery provided by USDA Farm Service Agency'}]}:{sources:[{format:'osm-overpass-json'}]});type='application/json';}else data='';response.writeHead(200,{'Content-Type':type});response.end(data);});
await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const report={viewport:{width:390,height:844},sourceOnlyDiffs:[],creditOnlyNAIP:false};
try{browser=await chromium.launch({channel:'chrome',headless:true});let baseline;
for(const version of ['old','new']){const page=await browser.newPage({viewport:report.viewport});await page.goto(`http://127.0.0.1:${server.address().port}/?version=${version}&world=/source/`);await page.waitForSelector('#world-credits[data-status=loaded]');const shots=[];for(const state of ['closed','open']){if(state==='open')await page.getByRole('button',{name:'About / credits'}).click();shots.push(await page.screenshot());await writeFile(resolve(out,version+'-'+state+'.png'),shots.at(-1));}if(version==='old')baseline=shots;else for(let j=0;j<2;j++){const a=PNG.sync.read(baseline[j]).data,b=PNG.sync.read(shots[j]).data;let max=0,count=0;for(let k=0;k<a.length;k++){const d=Math.abs(a[k]-b[k]);max=Math.max(max,d);if(d)count++;}assert.equal(count,0);report.sourceOnlyDiffs.push({state:j?'open':'closed',max,differingBytes:count});}await page.close();}
const page=await browser.newPage({viewport:report.viewport});await page.goto(`http://127.0.0.1:${server.address().port}/?world=/credit/`);await page.waitForSelector('#world-credits[data-status=loaded]');await page.getByRole('button',{name:'About / credits'}).click();assert.equal(await page.getByText('NAIP imagery provided by USDA Farm Service Agency',{exact:true}).isVisible(),true);await page.screenshot({path:resolve(out,'credit-only-naip.png')});report.creditOnlyNAIP=true;await writeFile(resolve(out,'evidence.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));await page.close();}finally{await browser?.close();await new Promise(r=>server.close(r));}
